const mongoose = require("mongoose");

const aaarecsSchema = new mongoose.Schema({
  svordnum: String,
  d2000user: String,
  dispnum: Number,
  data1: String,
  tcode1: String,
  tcode2: String,
  loc: String,
  landmark_d: String,
  city_break: String,
  vehicle: String,
  waittime: String,
  adr: String,
  pum: String,
  name: String,
  notes: String,
  ac: String,
  qu: String,
  pg: String,
  xs: String,
  ph1: String,
  ph2: String,
  yearcar: String,
  makecar: String,
  modelcar: String,
  colorcar: String,
  sentover: Boolean,
  whenappend: Date,
  whensent: Date,
  data2: String,
  data3: String,
  data4: String,
  aaaplus: Boolean,
  aaaplusmil: Number,
  aaamemtype: String,
  station: String,
  licensenum: String,
  towdest: String,
  printedtim: String,
  printeddat: Date,
  ptatime: String,
  comment1: String,
  comment2: String,
  statuseta: String,
  dcall: String,
  dref: String,
  dcompany: String,
  dscompany: String,
  daccount: String,
  dpriority: String,
  dreceived: String,
  dlicense: String,
  dyear: String,
  dmake: String,
  dcolor: String,
  dmodel: String,
  dloc: String,
  dmap: String,
  dxstreet: String,
  dcontact: String,
  dcontact2: String,
  dpum: String,
  dnotes: String,
  dnotes2: String,
  dnotes3: String,
  dnotes4: String,
  dnotes5: String,
  dnotes6: String,
  deta: String,
  dreason: String,
  dmembnum: String,
  ddest: String,
  dvin: String,
  data_feed: String,
  lastfield: Boolean,
});

const AaaRecs = mongoose.model("AaaRecs", aaarecsSchema);

module.exports = AaaRecs;
