const mongoose = require("mongoose");

const receivedSchema = new mongoose.Schema({
  dispnum: Number,
  invoicenum: { type: String, maxlength: 10 },
  towtagnum: { type: String, maxlength: 10 },
  datepaid: Date,
  datetime: Date,
  enterbywho: { type: String, maxlength: 14 },
  custnum: { type: String, maxlength: 8 },
  callactnum: { type: String, maxlength: 8 },
  paytype: { type: String, maxlength: 3 },
  trans_paya: { type: mongoose.Decimal128, max: 9999999999.99 },
  amount: { type: mongoose.Decimal128, max: 9999999999999.9999 },
  referencen: { type: String, maxlength: 22 },
  creationda: Date,
  ccnumber: { type: String, maxlength: 25 },
  ccexpdate: { type: String, maxlength: 5 },
  chknumber: { type: String, maxlength: 12 },
  whopayed: { type: String, maxlength: 20 },
  computer_n: { type: String, maxlength: 50 },
  last_edit: Date,
  whenappend: Date,
  paynote: { type: String, maxlength: 200 },
  batchpay: Boolean,
  calltype: { type: String, maxlength: 2 },
  storage: { type: mongoose.Decimal128, max: 999999999999.99 },
  liens: { type: mongoose.Decimal128, max: 999999999999.99 },
  towfee: { type: mongoose.Decimal128, max: 999999999999.99 },
  carsales: { type: mongoose.Decimal128, max: 999999999999.99 },
  editbywho: { type: String, maxlength: 14 },
  drawer: Number,
  voideddt: Date,
  vcomputer_: { type: String, maxlength: 50 },
  vdrawer: Number,
  voided: Boolean,
  relpass: { type: String, maxlength: 6 },
  history: Boolean,
  glaccount: { type: String, maxlength: 12 },
  glsub: { type: String, maxlength: 5 },
  gldescript: { type: String, maxlength: 25 },
  import_tim: Date,
  import_fil: { type: String, maxlength: 30 },
  billtoname: { type: String, maxlength: 30 },
  batchnum: { type: String, maxlength: 15 },
  foxtow_id: { type: String, maxlength: 10 },
  datesent: Date,
  sentstatus: { type: String, maxlength: 20 },
  batch: Number,
  glposted: { type: String, maxlength: 60 },
  rec_contro: { type: String, maxlength: 15 },
  locked: Boolean,
});

const Received = mongoose.model("Received", receivedSchema);

module.exports = Received;
