const mongoose = require("mongoose");

const towmastSchema = new mongoose.Schema({
  dispnum: Number,
  towdate: Date,
  yearcar: { type: String, maxlength: 2 },
  makecar: { type: String, maxlength: 12 },
  modelcar: { type: String, maxlength: 15 },
  colorcar: { type: String, maxlength: 12 },
  calltype: { type: String, maxlength: 2 },
  datein: Date,
  dateout: Date,
  callactnum: { type: String, maxlength: 8 },
  refnumber: { type: String, maxlength: 15 },
  callname: { type: String, maxlength: 30 },
  licensest: { type: String, maxlength: 2 },
  licensenum: { type: String, maxlength: 7 },
  callphone: { type: String, maxlength: 18 },
  days: Number,
  storagetyp: { type: String, maxlength: 2 },
  whocalled: { type: String, maxlength: 15 },
  perday: { type: mongoose.Decimal128, max: 9999999999999999.9999 },
  perdaytota: { type: mongoose.Decimal128, max: 9999999999999999.9999 },
  vin: { type: String, maxlength: 17 },
  type: { type: String, maxlength: 1 },
  tagmonthye: { type: String, maxlength: 5 },
  bodytype: { type: String, maxlength: 12 },
  towedfrom: { type: String, maxlength: 60 },
  towedto: { type: String, maxlength: 60 },
  retowto: { type: String, maxlength: 60 },
  cross_stre: { type: String, maxlength: 40 },
  retowtodat: Date,
  deletecode: { type: String, maxlength: 2 },
  odometer: { type: String, maxlength: 7 },
  membernum: { type: String, maxlength: 20 },
  memnumexpd: { type: String, maxlength: 5 },
  lotsection: { type: String, maxlength: 4 },
  enterbywho: { type: String, maxlength: 14 },
  dispatcher: { type: String, maxlength: 8 },
  reason: { type: String, maxlength: 20 },
  itemgroup: { type: String, maxlength: 2 },
  liendout: Date,
  liendin: Date,
  lientype: { type: String, maxlength: 2 },
  lientypems: { type: String, maxlength: 15 },
  lienfee: { type: mongoose.Decimal128, max: 9999999999999999.9999 },
  lien_overr: Boolean,
  releaselic: { type: String, maxlength: 12 },
  condition: { type: String, maxlength: 43 },
  driveable: Boolean,
  keysinfo: { type: String, maxlength: 3 },
  holdnote: { type: String, maxlength: 20 },
  callremark: String,
  callremar2: { type: String, maxlength: 254 },
  aaacallnum: { type: String, maxlength: 10 },
  dispatched: Boolean,
  priority: { type: String, maxlength: 2 },
  zone: Number,
  equipment: { type: String, maxlength: 2 },
  creationda: Date,
  etahours: Number,
  etaminutes: Number,
  etadatetim: Date,
  regnametow: { type: String, maxlength: 30 },
  regname: { type: String, maxlength: 30 },
  regaddr1: { type: String, maxlength: 30 },
  regaddr2: { type: String, maxlength: 30 },
  regaddr3: { type: String, maxlength: 30 },
  regcity: { type: String, maxlength: 15 },
  regstate: { type: String, maxlength: 2 },
  regzip: { type: String, maxlength: 10 },
  lienvalue: { type: mongoose.Decimal128, max: 9999999999999999.9999 },
  liencvamt: { type: mongoose.Decimal128, max: 9999999999999999.9999 },
  datesold: Date,
  computer_n: { type: String, maxlength: 50 },
  last_edit: Date,
  whenappend: Date,
  vstatus: { type: String, maxlength: 20 },
  udfchar1: { type: String, maxlength: 1 },
  udfchar2: { type: String, maxlength: 2 },
  driverwith: Boolean,
  picture1: { type: String },
  picture2: { type: String },
  picture3: { type: String },
  general1: { type: String },
  general2: { type: String },
  geoloca: { type: String, maxlength: 15 },
  geolocb: { type: String, maxlength: 15 },
  geodesta: { type: String, maxlength: 15 },
  geodestb: { type: String, maxlength: 15 },
  georetowa: { type: String, maxlength: 15 },
  georetowb: { type: String, maxlength: 15 },
  stocknum: Number,
  printed462: Boolean,
  is462car: Boolean,
  bmw2002: Boolean,
  editbywho: { type: String, maxlength: 14 },
  shift: { type: String, maxlength: 2 },
  releasetyp: { type: String, maxlength: 2 },
  officer: { type: String, maxlength: 20 },
  trsdatetim: Date,
  drawer: Number,
  relpass: { type: String, maxlength: 6 },
  transport: Boolean,
  property: Boolean,
  history: Boolean,
  limoco: Boolean,
  prnrellib: Boolean,
  legname: { type: String, maxlength: 30 },
  legaddr1: { type: String, maxlength: 30 },
  legaddr2: { type: String, maxlength: 30 },
  legaddr3: { type: String, maxlength: 30 },
  legcity: { type: String, maxlength: 15 },
  legstate: { type: String, maxlength: 2 },
  legzip: { type: String, maxlength: 10 },
  prnlapdimp: Boolean,
  date1523: Date,
  auct_num: Number,
  auct_date: Date,
  ipaqfound: { type: String, maxlength: 1 },
  auction1: Boolean,
  auction2: Boolean,
  auction3: Boolean,
  tozone: Number,
  exportdt: Date,
  soldamt: { type: mongoose.Decimal128, max: 999999.99 },
  foxtow_id: { type: String, maxlength: 10 },
  webstatus1: { type: String, maxlength: 50 },
  webstatus2: { type: String, maxlength: 50 },
  aaaplus: Boolean,
  aaaplusmil: { type: mongoose.Decimal128, max: 999999.99 },
  latitude1: Number,
  longitude1: Number,
  latitude2: Number,
  longitude2: Number,
  vinresult: { type: String, maxlength: 150 },
  udfcnum1: { type: mongoose.Decimal128, max: 9999999999.99 },
  udfcnum2: { type: mongoose.Decimal128, max: 9999999999.99 },
  udfcchar1: { type: String, maxlength: 30 },
  udfcchar2: { type: String, maxlength: 30 },
  udfcdate1: Date,
  udfcdate2: Date,
  amnesty: Boolean,
  pinkslip: Boolean,
  recbooknum: Number,
  amnesty_pa: { type: mongoose.Decimal128, max: 9999999999999999.9999 },
  datesent: Date,
  sentstatus: { type: String, maxlength: 20 },
  batch: Number,
  collect: { type: String, maxlength: 15 },
  mapcord: { type: String, maxlength: 8 },
  area: { type: String, maxlength: 20 },
  glposted: { type: String, maxlength: 60 },
  party1name: { type: String, maxlength: 30 },
  party1addr: { type: String, maxlength: 30 },
  party1add2: { type: String, maxlength: 30 },
  party1city: { type: String, maxlength: 15 },
  party1stat: { type: String, maxlength: 2 },
  party1zip: { type: String, maxlength: 10 },
  party2name: { type: String, maxlength: 30 },
  party2addr: { type: String, maxlength: 30 },
  party2add2: { type: String, maxlength: 30 },
  party2city: { type: String, maxlength: 15 },
  party2stat: { type: String, maxlength: 2 },
  party2zip: { type: String, maxlength: 10 },
  collect_fl: Boolean,
  readytogo: Boolean,
  ftiresize: { type: String, maxlength: 12 },
  rtiresize: { type: String, maxlength: 12 },
  wposition: { type: String, maxlength: 4 },
  locked: Boolean,
  lacqnum: Number,
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Company",
    required: false,
  },
  towdrives: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Towdrive",
    },
  ],
});

const Towmast = mongoose.model("Towmast", towmastSchema);

module.exports = Towmast;
